### ISSUE TITLE
Cloud Foundations Compliance Dashboard Application Requirements Checklist

### ISSUE THREAD

**Issue by archiemilne** [archiemilne/Team2BrightsolidITP#13]
- [ ] We must create a working prototype of a web application (with corresponding APIs) which must allow customers of Cloud Foundations to view their compliance position using the provided inputs.
- [ ] All our source code must be maintained using a Source Code Management tool.
- [ ] All changes must be deployed using a Continuous Integration pipeline.
- [ ] The web application must have at least two views, one for the compliance summary dashboard and one for the compliance rule detailed report.
- [ ] The Compliance Summary Dashboard must display a top-level summary of the non-compliance status of each compliance rule.
- [ ] The Compliance Summary Dashboard must have the ability to drill down each compliance rule to a Compliance Rule Detailed Report.
- [ ] The Compliance Rule Detailed Report must provide the compliance status of each cloud resource based on the selected compliance rule in the Compliance Summary Dashboard.
- [ ] The Compliance Rule Detailed Report must allow users with the Compliance Manager role to set exceptions for non-compliant cloud resources by providing a justification in free text.
- [ ] The Compliance Rule Detailed Report must allow users with the Compliance Manager role to set a next review date of a non-compliant cloud resource.
- [ ] The data entered by users with the Compliance Manager role must be stored in an appropriate persistent data store.
- [ ] The web application must save a record of exceptions over time for audit purposes, creating new exception records when a Compliance Manager updates an exception.
- [ ] A Compliance Manager should be able to view all past exceptions for each cloud resource.
- [ ] If an exception is set for a cloud resource, both the Summary Dashboard and Detailed Report must treat the cloud resource as being compliant unless the next review date has already past.
- [ ] Compliance Managers and Compliance Auditor users must be able to view the justification, next review date and the name of the Compliance Manager for past exceptions.
- [ ] The web application must be able to authenticate users based on their roles.
- [ ] The web application must not allow customers to view other customer information.
- [ ] Compliance Managers must be able to create, update, suspend and view any exception.
- [ ] Compliance Auditors must be unable to create, update and suspend exceptions.
- [ ] All user types must be unable to delete an exception.
- [ ] The web application should be scalable for mobile and other small devices.
- [ ] The web application should follow the colour scheme posted by the client.
- [ ] The web application should have accessibility features, such as colour blind mode, using dark or light mode preferences set on the user’s device, dyslexia friendly font etc.
- [ ] The Compliance Dashboard could display a visual representation of the compliance state e.g. using red, orange, green.
- [ ] The Compliance Dashboard could have a button to filter non-compliant rules, or other filtering options.
- [ ] The Compliance Dashboard must display real-time data.
- [ ] The Compliance Dashboard data should be either refreshed automatically or have the option on the UI for the user to refresh manually.
- [ ] Files used in the web application (Input files zip) must be read in from a data store.
- [ ] Users must only have one role type.
